<?php require __DIR__.'/config.php'; $me=current_user(); if($me && $me['role']==='admin'){ header('Location: admin.php'); exit; } $today=date('Y-m-d'); $hist=array(); $lastIn=null; $lastOut=null; if($me){ $st=db()->prepare('SELECT * FROM attendance WHERE user_id=? ORDER BY created_at DESC LIMIT 20'); $st->execute(array($me['id'])); $hist=$st->fetchAll(PDO::FETCH_ASSOC); foreach($hist as $r){ if(!$lastIn && $r['type']==='in') $lastIn=$r; if(!$lastOut && $r['type']==='out') $lastOut=$r; } } function day_id($d){ $h=array('Sunday'=>'Minggu','Monday'=>'Senin','Tuesday'=>'Selasa','Wednesday'=>'Rabu','Thursday'=>'Kamis','Friday'=>'Jumat','Saturday'=>'Sabtu'); $b=array('Jan'=>'Jan','Feb'=>'Feb','Mar'=>'Mar','Apr'=>'Apr','May'=>'Mei','Jun'=>'Jun','Jul'=>'Jul','Aug'=>'Agu','Sep'=>'Sep','Oct'=>'Okt','Nov'=>'Nov','Dec'=>'Des'); $ts=strtotime($d); return $h[date('l',$ts)].', '.date('d',$ts).' '.$b[date('M',$ts)].' '.date('Y',$ts).' - '.date('H:i',$ts).' WIB'; } ?><!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title><?=e(setting('app_name'))?></title><meta name="description" content="Absensi online modern dengan kamera wajah, validasi lokasi, riwayat absensi, izin, dan dashboard admin."><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/app.css"><script>window.CSRF='<?=csrf_token()?>';</script></head><body>
<?php if(!$me): ?>
<main class="anime-phone login-page">
  <section class="login-card neon-panel">
    <img class="login-avatar" src="<?=e(setting('avatar_img'))?>" alt="avatar">
    <h1><?=e(setting('app_name'))?></h1><p><?=e(setting('org_name'))?></p>
    <form id="loginForm" autocomplete="off"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input class="bot-trap" name="company" tabindex="-1" autocomplete="off"><label>Username / No HP<input name="identity" required placeholder="Masukkan akun"></label><label>Password<input type="password" name="password" required placeholder="Masukkan password"></label><button class="blue-btn">Masuk</button><div class="form-msg"></div></form>
  </section>
</main>
<?php else: ?>
<div class="anime-phone">
  <header class="top-zone">
    <button class="hamburger" id="openSide" aria-label="Menu"><span></span><span></span><span></span></button>
    <button class="bell" aria-label="Notifikasi"><span></span></button>
    <div class="profile-row"><img class="avatar-ring" src="<?=e($me['avatar']?$me['avatar']:setting('avatar_img'))?>" alt="avatar"><div><h2>Hallo, <b><?=e($me['name'])?></b></h2><p>Selamat datang kembali!</p><em class="date-pill"><svg viewBox="0 0 24 24"><path d="M7 3v3M17 3v3M4 8h16M6 5h12a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2Z"/></svg><?=e(setting('date_label'))?></em></div></div>
    <img class="hero-boy" src="<?=e(setting('hero_img'))?>" alt="hero"><div class="vertical-jp">出<br>席<br><b>する</b></div>
  </header>
  <main class="content-scroll">
    <section class="panel status-card"><h3><svg viewBox="0 0 24 24"><path d="M7 3v3M17 3v3M4 8h16M6 5h12a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2Z"/></svg>Status Hari Ini</h3><div class="status-inside"><span class="big-check"></span><div><b>Belum Absen</b><p>Silakan lakukan absensi masuk<br>dan pulang.</p></div><img src="<?=e(setting('status_img'))?>" alt="status"></div></section>
    <section class="panel menu-panel tab-page active" id="homePage"><h3><span class="round-icon purple">◷</span>Absensi Masuk</h3><button class="face-card locked-feature" data-locked="face" type="button"><span class="face-scan"></span><span><b>Absensi Wajah</b><small>Fitur dikunci untuk pegawai terbatas</small></span><em class="lock-badge">Terkunci</em></button></section>
    <section class="panel map-panel"><h3><span class="round-icon cyan">⌖</span>Lokasi Anda</h3><div class="map-box real-map"><iframe loading="lazy" referrerpolicy="no-referrer-when-downgrade" src="https://www.openstreetmap.org/export/embed.html?bbox=107.603%2C-6.920%2C107.616%2C-6.909&amp;layer=mapnik&amp;marker=-6.914744%2C107.609810"></iframe><span class="map-lock">Maps dikunci</span></div><div class="office-float"><span class="small-pin">⌖</span><div><b><?=e(setting('office_name'))?></b><p><?=e(setting('office_address'))?></p></div><button id="checkArea" class="area-ok locked-area" type="button" disabled>🔒 Maps Dikunci</button></div></section>
    <section class="panel history-panel"><h3><span class="round-icon cyan">◷</span>Riwayat Absensi <a href="#" data-tab="historyPage">Lihat semua ›</a></h3><div class="history-list">
      <div class="history-line"><span class="hist-icon green">↪</span><div><b>Masuk</b><p><?= $lastIn ? e(day_id($lastIn['created_at'])) : 'Kamis, 7 Mei 2026 - 08:15 WIB' ?></p></div><em class="green-pill">Tepat Waktu</em></div>
      <div class="history-line"><span class="hist-icon red">↩</span><div><b>Pulang</b><p><?= $lastOut ? e(day_id($lastOut['created_at'])) : 'Kamis, 7 Mei 2026 - 17:05 WIB' ?></p></div><em class="red-pill">Belum Absen</em></div>
    </div></section>
    <section class="panel tab-page" id="historyPage"><h3><span class="round-icon cyan">◷</span>Riwayat Lengkap</h3><?php if(!$hist): ?><p class="empty">Belum ada riwayat nyata. Silakan lakukan absensi.</p><?php endif; foreach($hist as $r): ?><div class="history-line"><span class="hist-icon <?=$r['type']==='in'?'green':'red'?>"><?=$r['type']==='in'?'↪':'↩'?></span><div><b><?=$r['type']==='in'?'Masuk':'Pulang'?></b><p><?=e(day_id($r['created_at']))?> • <?=round($r['distance_m'])?>m</p></div><em class="<?=$r['inside_area']?'green-pill':'red-pill'?>"><?=$r['inside_area']?'Dalam Area':'Luar Area'?></em></div><?php endforeach; ?></section>
    <section class="panel tab-page" id="izinPage"><h3><span class="round-icon purple">▤</span>Pengajuan Izin</h3><form id="leaveForm" class="neon-form"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><label>Jenis<select name="kind"><option>Izin</option><option>Sakit</option><option>Cuti</option><option>Dinas Luar</option></select></label><label>Mulai<input type="date" name="date_start" required></label><label>Sampai<input type="date" name="date_end" required></label><label>Alasan<textarea name="reason" required></textarea></label><button class="blue-btn">Kirim Izin</button><div class="form-msg"></div></form></section>
    <section class="panel tab-page" id="akunPage"><h3><span class="round-icon cyan">○</span>Akun</h3><div class="account-head"><img src="<?=e($me['avatar']?$me['avatar']:setting('avatar_img'))?>"><div><b><?=e($me['name'])?></b><p><?=e($me['position'])?> • <?=e($me['phone'])?></p></div></div><form id="passwordForm" class="neon-form"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><label>Password Lama<input type="password" name="old_password" required></label><label>Password Baru<input type="password" name="new_password" required minlength="6"></label><button class="blue-btn">Ubah Password</button><div class="form-msg"></div></form><a class="logout-btn" href="api.php?action=logout">Keluar</a></section>
  </main>
  <nav class="bottom-nav"><a class="active" data-tab="homePage"><span class="nav-home"></span>Beranda</a><a data-tab="historyPage"><span class="nav-clock"></span>Riwayat</a><a data-tab="izinPage"><span class="nav-doc"></span>Izin</a><a data-tab="akunPage"><span class="nav-user"></span>Akun</a></nav>
  <div class="side-backdrop" id="sideBackdrop"></div><aside class="user-side" id="userSide"><button id="closeSide">×</button><b><?=e(setting('app_name'))?></b><a data-tab="homePage">Beranda</a><a data-tab="historyPage">Riwayat</a><a data-tab="izinPage">Izin</a><a data-tab="akunPage">Akun</a><a href="api.php?action=logout">Keluar</a></aside>
</div>
<div class="camera-modal" id="cameraModal"><div class="camera-card"><button id="closeCamera">×</button><h3>Absensi Wajah</h3><p>Posisikan wajah di tengah kamera lalu simpan absensi.</p><video id="video" autoplay playsinline></video><canvas id="canvas" hidden></canvas><div class="modal-actions"><button class="soft-btn" id="checkLoc">Cek Maps</button><button class="blue-btn" id="captureBtn">Simpan Absensi</button></div><div id="cameraMsg" class="form-msg"></div></div></div>
<?php endif; ?><script>window.FEATURE_LOCKS={face:true,maps:true};</script><script src="assets/app.js"></script></body></html>
